### ISSUE TITLE
Cors Filter not working on external Tomcat Container

### ISSUE THREAD

**Issue by iveeshal** [spring-guides/gs-rest-service-cors#11]
Hi I enabled one of my APIS with @CrossOrigin annotation.

When I run using spring boot tomcat embedded container it works fine but while deploying the war to an external tomcat container ,it fails.

Any reason why? Morever I am using spring security in my project too

**Comment by sdeleuze** [comment]
Did you configure the Cors filter on you external container as the first one ?

**Comment by dsyer** [comment]
No response. Assume pilot error (it will work if the filter is declared).
