### ISSUE TITLE
greeting method in GreetingController is missing @ResponseBody annotation.

### ISSUE THREAD

**Issue by Nico769** [spring-guides/gs-rest-service-cors#30]
The guide mentions `@ResponseBody` (`README.adoc`, line 219) but the annotation is both missing in the `GreetingController` listing and the accompanying example code.

I'd be happy to make a PR :).

Thank you.

**Comment by Buzzardo** [comment]
Please do make a PR for it. Thanks.

**Comment by dsyer** [comment]
You don't need a `@ResponseBody` in a `@RestController`. So better to fix the README text IMO.

**Comment by Nico769** [comment]
> You don't need a `@ResponseBody` in a `@RestController`. So better to fix the README text IMO.

Thanks for the clarification (I'm still learning Spring in tandem with Spring Boot :)).

> Please do make a PR for it. Thanks.

Great! You're welcome.
