### ISSUE TITLE
Incorrect link to "Consuming a RESTful Web Service with jQuery" in "Enabling Cross Origin Requests for a RESTful Web Service" documentation

### ISSUE THREAD

**Issue by leewebb** [spring-guides/gs-rest-service-cors#33]
The [Test the service](https://spring.io/guides/gs/rest-service-cors/#_test_the_service) section of [Enabling Cross Origin Requests for a RESTful Web Service](https://spring.io/guides/gs/rest-service-cors/) has an incorrect link reference to [Consuming a RESTful Web Service with jQuery](https://spring.io/guides/gs/consuming-rest-jquery/):

> This is essentially the REST client created in [Consuming a RESTful Web Service with jQuery](https://spring.io/guides/gs/rest-service/gs/consuming-rest-jquery/), modified slightly to consume the service when it runs on localhost at port 8080. See that guide for more details on how this client was developed

### Steps to reproduce

- Click the link to "Consuming a RESTful Web Service with jQuery" in the [Test the service](https://spring.io/guides/gs/rest-service-cors/#_test_the_service) section

### Expected Results

- Navigates to [Consuming a RESTful Web Service with jQuery](https://spring.io/guides/gs/consuming-rest-jquery/)

### Actual Results

- Generates a 404 response as the link incorrectly contains `rest-service/gs/` in `https://spring.io/guides/gs/rest-service/gs/consuming-rest-jquery/ `

**Comment by Buzzardo** [comment]
We no longer maintain the jQuery guide. The paragraph should be removed. I'm going to label is a good first issue for folks to get started on.

**Comment by Buzzardo** [comment]
I went ahead and fixed it in https://github.com/spring-guides/gs-rest-service-cors/commit/e567a0a827c82f39771ef00e45db288cecb9114d
