### ISSUE TITLE
Update Spring Boot to the latest version

### ISSUE THREAD

**Issue by robertmcnees** [spring-guides/gs-rest-service-cors#36]
Update the guide to use the most recent Spring Boot version.

Files that require changes are:

```
initial/build.gradle
initial/pom.xml
complete/build.gradle
complete/pom.xml
```

**Comment by yr1404** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by robertmcnees** [comment]
Hi @yr1404 .  Thank you for your interest!  Please feel free to submit a PR for this issue.  The first valid PR that we get we will merge.

If you don't get the chance to work on this issue there should be other opportunities.  Spring Boot releases approximately once per month so frequent updates will be needed.  Additionally this same issue exists in about 16 other repositories in the spring-guides org.

Thanks again for your interest!  If you need help learning the processes [here is a great video](https://www.youtube.com/watch?v=kHZzQR9ntvc) by two Spring Engineers on how to contribute to open source.

**Comment by yr1404** [comment]
Thank for suggesting the video @robertmcnees.

**Comment by robertmcnees** [comment]
Thanks for the PR @yr1404 !  It has been merged.  I'll close this issue for now.  We will likely have more upgrade possibilities in the future.
