### ISSUE TITLE
update this guide once Spring Framework 4.2 + Boot 1.3 are released

### ISSUE THREAD

**Issue by bclozel** [spring-guides/gs-rest-service-cors#6]
See [SPR-9278](https://jira.spring.io/browse/SPR-9278) for comprehensive CORS support in Spring MVC.

cc @sdeleuze

**Comment by sdeleuze** [comment]
See [this article](https://spring.io/blog/2015/06/08/cors-support-in-spring-framework) and this Spring Boot CORS support issue https://github.com/spring-projects/spring-boot/issues/3052 for more details ...

**Comment by gregturn** [comment]
@sdeleuze Do you mind coming back and doing this modification when Spring Boot 1.3 hits GA? We have decided to keep the guides on stable releases.

**Comment by sdeleuze** [comment]
@gregturn Sure, thanks for the info. In any case that was my intention, that's why I have not merged PR https://github.com/spring-guides/gs-rest-service-cors/pull/7 yet.

**Comment by ceefour** [comment]
Oh may be mention Spring Data REST ... https://jira.spring.io/browse/DATAREST-573
