### ISSUE TITLE
Guide is not working as of 2015-11-25

### ISSUE THREAD

**Issue by michael-simons** [spring-guides/gs-rest-service-cors#9]
Sorry, guys, checked it out, started to instances
mvn spring-boot:run
mvn spring-boot:run -Dserver.port=9000
followed the tutorial, no Access-Control-Allow-Origin present as a response head, so the demo doesn't work.

Are we missing something in configuration or is @CrossOrigin annotation broken?

**Comment by dsyer** [comment]
Works for me. Are you sure you followed the guide precisely? You are supposed to look at the result in your browser using localhost:9000.

**Comment by michael-simons** [comment]
Yes, i am.
![firefox_cors](https://cloud.githubusercontent.com/assets/526383/11400791/90d89628-938f-11e5-9367-c00fe3005f3a.png)

But, when i was creating that screenshot, i realized my error, been using 127.0.0.1 all alone and i didn't notice that Spring only adds those headers in a real cross origin request. If i simulate one with curl

```
curl -H "Origin: http://localhost:9000" --verbose http://localhost:8080/greeting
```

is see them.

So, as alway, mea culpa. Sorry.

**Comment by dsyer** [comment]
Good. I think if you look carefully, the actual reason your browser test didn't work was because it sent "Origin: http://127.0.0.1:9000", where the endpoint is annotated to only allow "http://localhost:9000".

**Comment by michael-simons** [comment]
Yeah, i noticed that :) :+1: 

What i learned is, that the headers in questions are only sent by the native method when it's actually a CORS request (or CORS preflight OPTIONS request). Nearly all other filter based solutions are always adding them. 

Anyway, sorry that i wasted your time and thanks for clarifying the situation.
